-- MySQL Script generated by MySQL Workbench
-- Sat May 23 11:49:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onlinestoredb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onlinestoredb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlinestoredb` DEFAULT CHARACTER SET utf8 ;
USE `onlinestoredb` ;

-- -----------------------------------------------------
-- Table `onlinestoredb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`articulos` (
  `articulo_id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `existencia` INT NOT NULL,
  PRIMARY KEY (`articulo_id`),
  UNIQUE INDEX `articulo_id_UNIQUE` (`articulo_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`cupones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`cupones` (
  `cupon` VARCHAR(45) NOT NULL,
  `tipo_descuento` VARCHAR(45) NOT NULL,
  `descuento` INT NOT NULL,
  `aplicado` INT NOT NULL,
  UNIQUE INDEX `cupon_UNIQUE` (`cupon` ASC),
  PRIMARY KEY (`cupon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`ventas` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cliente_id` INT NOT NULL,
  `importe` DECIMAL NOT NULL,
  `iva` DECIMAL NOT NULL,
  `descuento` DECIMAL NULL,
  `total` DECIMAL NOT NULL,
  `cupon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `fk_ventas_clientes_idx` (`cliente_id` ASC),
  INDEX `fk_ventas_cupones1_idx` (`cupon` ASC),
  UNIQUE INDEX `folio_UNIQUE` (`folio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`detalle_ventas` (
  `detalle_id` INT NOT NULL AUTO_INCREMENT,
  `folio` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL NULL,
  `precio_total` DECIMAL NULL,
  PRIMARY KEY (`detalle_id`),
  INDEX `fk_detalle_ventas_ventas1_idx` (`folio` ASC),
  INDEX `fk_detalle_ventas_articulos1_idx` (`articulo_id` ASC),
  UNIQUE INDEX `detalle_id_UNIQUE` (`detalle_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`usuarios` (
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`temporal` (
  `temporal_id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `pu` DECIMAL NULL,
  `pt` DECIMAL NULL,
  `articulo_id` INT NOT NULL,
  PRIMARY KEY (`temporal_id`),
  INDEX `fk_temporal_articulos1_idx` (`articulo_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onlinestoredb`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinestoredb`.`configuracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iva` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
