-- MySQL Script generated by MySQL Workbench
-- Sat May 16 01:26:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`usuarios` (
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`montos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`montos` (
  `monto_id` INT NOT NULL AUTO_INCREMENT,
  `monto` FLOAT NOT NULL,
  PRIMARY KEY (`monto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`plazos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`plazos` (
  `plazo_id` INT NOT NULL AUTO_INCREMENT,
  `plazo` INT NOT NULL,
  PRIMARY KEY (`plazo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`intereses` (
  `interes_id` INT NOT NULL AUTO_INCREMENT,
  `interes` INT NOT NULL,
  PRIMARY KEY (`interes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`prestamos` (
  `prestamo_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `monto_id` INT NOT NULL,
  `interes_id` INT NOT NULL,
  `plazo_id` INT NOT NULL,
  PRIMARY KEY (`prestamo_id`),
  INDEX `fk_prestamos_clientes_idx` (`cliente_id` ASC),
  INDEX `fk_prestamos_montos1_idx` (`monto_id` ASC),
  INDEX `fk_prestamos_intereses1_idx` (`interes_id` ASC),
  INDEX `fk_prestamos_plazos1_idx` (`plazo_id` ASC),
  CONSTRAINT `fk_prestamos_clientes`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `testdb`.`clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_montos1`
    FOREIGN KEY (`monto_id`)
    REFERENCES `testdb`.`montos` (`monto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_intereses1`
    FOREIGN KEY (`interes_id`)
    REFERENCES `testdb`.`intereses` (`interes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_plazos1`
    FOREIGN KEY (`plazo_id`)
    REFERENCES `testdb`.`plazos` (`plazo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`amortizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`amortizaciones` (
  `amortizacion_id` INT NOT NULL AUTO_INCREMENT,
  `fecha_pago` DATETIME NOT NULL,
  `prestamo` FLOAT NOT NULL,
  `interes` FLOAT NOT NULL,
  `abono` FLOAT NOT NULL,
  `prestamo_id` INT NOT NULL,
  PRIMARY KEY (`amortizacion_id`),
  INDEX `fk_amortizaciones_prestamos1_idx` (`prestamo_id` ASC),
  CONSTRAINT `fk_amortizaciones_prestamos1`
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `testdb`.`prestamos` (`prestamo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
