-- MySQL Script generated by MySQL Workbench
-- Thu May 21 10:07:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_db` DEFAULT CHARACTER SET utf8;
USE `test_db` ;

-- -----------------------------------------------------
-- Table `test_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`usuarios` (
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`montos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`montos` (
  `monto_id` INT NOT NULL AUTO_INCREMENT,
  `monto` FLOAT NOT NULL,
  PRIMARY KEY (`monto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`plazos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`plazos` (
  `plazo_id` INT NOT NULL AUTO_INCREMENT,
  `plazo` INT NOT NULL,
  PRIMARY KEY (`plazo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`intereses` (
  `interes_id` INT NOT NULL AUTO_INCREMENT,
  `interes` INT NOT NULL,
  PRIMARY KEY (`interes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`prestamos` (
  `prestamo_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `monto_id` INT NOT NULL,
  `interes_id` INT NOT NULL,
  `plazo_id` INT NOT NULL,
  PRIMARY KEY (`prestamo_id`),
  INDEX `fk_prestamos_clientes_idx` (`cliente_id` ASC),
  INDEX `fk_prestamos_montos1_idx` (`monto_id` ASC),
  INDEX `fk_prestamos_intereses1_idx` (`interes_id` ASC),
  INDEX `fk_prestamos_plazos1_idx` (`plazo_id` ASC),
  CONSTRAINT `fk_prestamos_clientes`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `test_db`.`clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_montos1`
    FOREIGN KEY (`monto_id`)
    REFERENCES `test_db`.`montos` (`monto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_intereses1`
    FOREIGN KEY (`interes_id`)
    REFERENCES `test_db`.`intereses` (`interes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamos_plazos1`
    FOREIGN KEY (`plazo_id`)
    REFERENCES `test_db`.`plazos` (`plazo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`amortizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`amortizaciones` (
  `amortizacion_id` INT NOT NULL AUTO_INCREMENT,
  `numero_pago` INT NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `prestamo` FLOAT NOT NULL,
  `interes` FLOAT NOT NULL,
  `abono` FLOAT NOT NULL,
  `prestamo_id` INT NOT NULL,
  `amortizacionescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`amortizacion_id`),
  INDEX `fk_amortizaciones_prestamos1_idx` (`prestamo_id` ASC),
  CONSTRAINT `fk_amortizaciones_prestamos1`
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `test_db`.`prestamos` (`prestamo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_db`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_db`.`ventas` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `importe` FLOAT NULL,
  `iva` FLOAT NULL,
  `descuento` FLOAT NULL,
  `total` FLOAT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `fk_ventas_clientes1_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `test_db`.`clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
